### ISSUE TITLE
Suggestion: Deploy Wi-Fi Network Configurations

### ISSUE THREAD

**Issue by lukebarone** [FOGProject/fog-client#104]
As an extra option, being able to specify the Wireless Network configuration would save a lot of time if it was deployed automatically when the client connect. My current approach is to deploy it with PDQ after the system comes online.

**Comment by FinancedHydra** [comment]
Using a Snapin should allow you to do that. Associated snapins automatically run after a computer has been imaged, and the client first connects.

You can find an example video of deploying a wireless profile using Snapin Packs here: https://wiki.fogproject.org/wiki/index.php?title=SnapinPacks#Batch_Script_-_deploy_wireless_profile

Note that the script in the example uses a hard-coded path for the wireless profile XML. Instead you should use `%~dp0` to reference the snapin's current directory. That way the script doesn't rely on hard-coded file paths that may change.

**Comment by lukebarone** [comment]
I followed the directions there, as well as placing the `%!dp0` into the script, but the client is not joining the Wi-Fi.

Checking the FOG log, under the `SnapinClient` section, I'm seeing lots of "Response: No snapins", even though they are assigned under the Snapins part on FOG.

I'll post on the FOG forums about this issue. I still believe it would be nice to deploy the Wi-Fi networks directly from the FOG interface, since Mac OSX, Windows and Linux all store their Wi-Fi configurations in different areas, in the mean time.

**Comment by FinancedHydra** [comment]
I'm closing this issue for now as you have a viable work-a-round in the mean time and the feature would require frontend, backend and client changes.  Hopefully we can take another look at this feature when we have less tickets in our backlog.
