### ISSUE TITLE
Printer config file not read

### ISSUE THREAD

**Issue by Blank-Vcf** [FOGProject/fog-client#106]
Try to push a custom config file with fog to enable secure printing.
Config file is export with rundll to dat file
Config file is push in local folder in image.
In printer configuration local path is specified as C:\printers\konica\Konica_secure.dat

The printer is correctly created but with default configuration.
With a procmon i saw the rundll command is executed has:
`"C:\Windows\System32\rundll32.exe"  printui.dll,PrintUIEntry /if /b "PRN_TEST_Kon" /f "C:\printers\konica\KOAXOA__.INF" /r "192.168.37.252" /m "KONICA MINOLTA 558SeriesPS" /q`
and my dat file is never read.
And in fog log:

> ------------------------------------------------------------------------------
> --------------------------------PrinterManager--------------------------------
> ------------------------------------------------------------------------------
>  09/10/2018 16:08 Client-Info Client Version: 0.11.12
>  09/10/2018 16:08 Client-Info Client OS:      Windows
>  09/10/2018 16:08 Client-Info Server Version: 1.4.4
>  09/10/2018 16:08 Middleware::Response Success
>  09/10/2018 16:08 PrinterManager Adding printers
>  09/10/2018 16:08 Printer Adding: PRN_TEST_Kon
>  09/10/2018 16:08 PrinterManager PrintUI return code = 0
>  09/10/2018 16:08 PrinterManager Configuring PRN_TEST_Kon
>  09/10/2018 16:08 PrinterManager PrintUI return code = 0
>  09/10/2018 16:08 PrinterManager Restarting spooler
> ------------------------------------------------------------------------------

**Comment by Sebastian-Roth** [comment]
@Blank-Vcf Sorry for not responding any earlier. We don't have the capacity to look into all issues that are being reported and so it took some time to get to this.

Thanks for finding the command via procmon and posting here as this should make it easier for us to find what is going on. I might have found what's wrong but I need more time to fix and test this.

I need to ask you to update to the latest version (FOG server 1.5.4 and fog-client 0.11.16) as we usually don't backport fixes to older versions. Please let me know when you have updated.

**Comment by Blank-Vcf** [comment]
If i backup with /ss m g
```
- g: Use to store the information in the printer s global DEVmode structure.
- m: Use to store the minimal settings for the printer. This is equivalent to specifying 2 d, and g.
```
restoring with m f g p cause windows error , surely because printer name not available in config file

**Comment by Blank-Vcf** [comment]
Upgraded dev server to 1.5.4 , the config form is gone
![image](https://user-images.githubusercontent.com/16317786/48353812-9a1bea80-e690-11e8-9c7d-f2ee3dd35d6f.png)

**Comment by Sebastian-Roth** [comment]
Phew ... this is getting worse. Sorry for that! I will look into this in the next couple of days!

**Comment by Sebastian-Roth** [comment]
Hey @Blank-Vcf, sorry I lost track of this with too many other things needed fixing. As I have not played much with the printer stuff it just takes a fair amount of time for me to work myself into this and get things up to be able to test as well.

So I started by adding back the "Printer Config File" field to the web UI. Seems like this was lost when a major refactoring was done. Not very many people seem to use FOG to manage printers and no one noticed it.

May I ask you to upgrade to the current development version to get back the field in the GUI and we'll tackle the actual issue in the fog-client then.

```
cd /path/to/fogprojectrepo
git checkout dev-branch
git pull
cd bin
./installfog.sh
```

**Comment by Sebastian-Roth** [comment]
@Blank-Vcf Ok, I finally got around to build a new `Modules.dll` for you to test. Sorry again for the long delay! The change I made is changing the parameters from `m f g p` to `m r g p`. Please give it a try and let us know.

- Open command prompt with admin user rights and type: `net stop fogservice`.
- Go to `C:\Program Files (x86)\FOG` and rename `Modules.dll` e.g. to `Modules_orig.dll`.
- Extract the new one you find in the [Modules.zip attached to this message](https://github.com/FOGProject/fog-client/files/2660608/Modules.zip) and copy to `C:\Program Files (x86)\FOG`.
- In the command prompt type: `net start fogservice`.

You do not need to update your FOG server to the dev-branch if you do not want to at the moment. The config file setting for your printer should still be in the database and will be used by the client. Just for modification it is easier to use the web UI but you could still change the value using the mysql command line client or phpmyadmin.

PS: Promise I will react faster from now on!

**Comment by Blank-Vcf** [comment]
we are running under windows 10 1709. For printer configuration, you have the printer tab and user tab that store config in HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Print\Printers\ and HKCU\Printers\DevModePerUser\ ; HKLM should be writable to system account.

I'll test your dll only next week.

**Comment by Sebastian-Roth** [comment]
@Blank-Vcf Were you able to test the provided DLL. Did it work for you?

**Comment by Sebastian-Roth** [comment]
@Blank-Vcf Any news on this?

**Comment by Sebastian-Roth** [comment]
Will close now as we have not heard back for a long time.
