### ISSUE TITLE
Set FOG infos as environment variables when snap-in is started

### ISSUE THREAD

**Issue by mserve** [FOGProject/fog-client#109]
If a snapin is started, it has no information about its environment in terms of FOG server, host id etc. Hence, it is quite complicated for a snap-in to use the FOG API if it needs further information, e.g. each snap-in needs its own logic to determine the MAC adress of the host - although this information is stored in FOG client.

It would be very useful if typical FOG infos are set as environment variables when a snap-in is started, eg:

    FOG_URL=https://my-fog-server.mycompany.local/fog
    FOG_SNAPIN_TASK_ID=123
    FOG_MAC_ADRESSES=12:23:34:43:32:21|45:67:89:98:76:54

This enhancement should be straight forward, as FOG client has those infos (well, at least via Zazzle if I got the code right...).

 Just after https://github.com/FOGProject/fog-client/blob/master/Modules/SnapinClient/SnapinClient.cs#L203 one could simply [add the environment variables](https://docs.microsoft.com/de-de/dotnet/api/system.diagnostics.processstartinfo.environmentvariables?view=netframework-4.0) if I properly understood the API docs 

    process.StartInfo.EnvironmentVariables.Add("FOG_URL", Configuration.ServerAddress);
    process.StartInfo.EnvironmentVariables.Add("FOG_SNAPIN_TASK_ID", snapin.JobTaskID);
    process.StartInfo.EnvironmentVariables.Add("FOG_MAC_ADRESSES", Configuration.MACAddresses());

Unfortunately, I normally develop JS, PHP and Java and do not have any .NET dev environment to properly make this change by myself and provide a PR, but maybe another developer could give it a try...

**Comment by Sebastian-Roth** [comment]
@mserve Definitely something we can do. Thanks for the detailed information on this. I see that setting up a build environment for this is quite an endeavor. I will add those things for you in the next days and post an update here.

**Comment by Sebastian-Roth** [comment]
@mserve Please give this DLL a try: 

Stop the FOGService on your client machine. Put the new DLL in place (named `Modules.dll`) and start the FOGService again. See if you have the environment.

**Comment by mserve** [comment]
@Sebastian-Roth works perfectly, I started following "Snap-In"

    get-item env: | Out-File C:\Users\User\Desktop\env.txt

on my virtual "snap-in development" client and all three variables appeared

    Name                           Value                                                                                   
    ----                           -----                                                                                   
    Path                           C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPo...
    PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL                              
    USERDOMAIN                     WORKGROUP                                                                               
    PROCESSOR_ARCHITECTURE         x86                                                                                     
    ProgramW6432                   C:\Program Files                                                                        
    DriverData                     C:\Windows\System32\Drivers\DriverData                                                  
    PUBLIC                         C:\Users\Public                                                                         
    APPDATA                        C:\Windows\system32\config\systemprofile\AppData\Roaming                                
    windir                         C:\Windows                                                                              
    LOCALAPPDATA                   C:\Windows\system32\config\systemprofile\AppData\Local                                  
    CommonProgramW6432             C:\Program Files\Common Files                                                           
    FOG_MAC_ADRESSES               2E:13:5C:4C:78:68                                                                       
    TMP                            C:\Windows\TEMP                                                                         
    USERPROFILE                    C:\Windows\system32\config\systemprofile                                                
    ProgramFiles                   C:\Program Files (x86)                                                                  
    PROCESSOR_LEVEL                15                                                                                      
    CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files                                                     
    COMPUTERNAME                   3333-L01                                                                                
    PROCESSOR_ARCHITEW6432         AMD64                                                                                   
    USERNAME                       3333-L01$                                                                               
    NUMBER_OF_PROCESSORS           4                                                                                       
    PROCESSOR_IDENTIFIER           Intel64 Family 15 Model 6 Stepping 1, GenuineIntel                                      
    SystemRoot                     C:\Windows                                                                              
    ComSpec                        C:\Windows\system32\cmd.exe                                                             
    TEMP                           C:\Windows\TEMP                                                                         
    ProgramFiles(x86)              C:\Program Files (x86)                                                                  
    CommonProgramFiles             C:\Program Files (x86)\Common Files                                                     
    PROCESSOR_REVISION             0601                                                                                    
    FOG_URL                        http://192.168.0.112/fog                                                                
    PSModulePath                   C:\Program Files\WindowsPowerShell\Modules;WindowsPowerShell\Modules;C:\Program Files...
    ALLUSERSPROFILE                C:\ProgramData                                                                          
    SystemDrive                    C:                                                                                      
    OS                             Windows_NT                                                                              
    PSExecutionPolicyPreference    Bypass                                                                                  
    ProgramData                    C:\ProgramData                                                                          
    FOG_SNAPIN_TASK_ID             4                                                                                       

That saves much time in re-packing snapin-packs for different environment (e.g., as in our case, development and production server). Thank you!

**Comment by Sebastian-Roth** [comment]
@mserve Thanks for your quick feedback. I just pushed the code change in 8944e85. Will be part of the next release.

**Comment by mserve** [comment]
@Sebastian-Roth minor typo - my fault - typical error by native German speakers ;)
it would be better to use FOG_MAC_A**D**DRESSES with double-D

**Comment by Sebastian-Roth** [comment]
@mserve Ahhhh right! Thanks for letting me know. Usually I pay attention to this kind of things but missed that one. I'll fix this for the official build. Should I also update the uploaded DLL for you?

**Comment by mserve** [comment]
I am fine with the official build, we won't update our clients before the official release

Am 16. Juli 2019 00:18:02 MESZ schrieb Sebastian-Roth <notifications@github.com>:
