### ISSUE TITLE
version displayed not correct

### ISSUE THREAD

**Issue by florentlagoda** [FOGProject/fog-client#127]
Hi,
Thanks to have update client to 0.12.0 !
Not a big problem but the version displayed on Windows (programs control panel) is 0.11.19 instead of 0.12.0

**Comment by Sebastian-Roth** [comment]
@florentlagoda Thanks heaps for testing and letting me know!

I knew I would miss something important this time. Will fix this soon!

**Comment by Sebastian-Roth** [comment]
@florentlagoda Ok, just updated the release and binaries to show the correct version. If you update to the latest `dev-branch` it will pull the new client and auto-updating the fog-client should still work perfectly fine according to my tests.
