### ISSUE TITLE
Delete old MAC addresses

### ISSUE THREAD

**Issue by banaipe95** [FOGProject/fog-client#129]
When the host communicates with fog it will send every mac address relative to it's network cards.
Sometimes these network cards may change and it leaves behind the old mac address.

This may conflict if for example the old network card is installed in another computer. Then the two hosts will have the same network mac address.

**Comment by Sebastian-Roth** [comment]
@banaipe95 So what are you proposing should be done?

If you want to delete old MAC addresses from your FOG server you can use the web UI and remove additional MACs. Make sure the fog-client software is not active on that host as it might re-add the additional MACs. If you can't delete the MACs through the web UI there is always a way to manually delete those from the database (table `hostMAC`).

The other thing you want to look into is the **QUICKREG PENDING MAC FILTER** in FOG Setttings -> FOG Configuration -> FOG Client - Host Register. Just be aware that there was an issue in that feature up until FOG version 1.5.8 and you need to be on the very latest (currently 1.5.9-RC2) to be able to use wildcards MACs in this field.
