### ISSUE TITLE
Files  sysv-rc-config and chkconfig missing

### ISSUE THREAD

**Issue by DKImprowised** [FOGProject/fog-client#130]
Not able to install client in Manjaro Linux

commands: mono SmartInstaller.exe

error: cannot find the specified files

![IMG-20201105-WA0007](https://user-images.githubusercontent.com/72780358/98244652-c7f14c80-1f95-11eb-8e0d-96d7814765bc.jpg)

**Comment by Sebastian-Roth** [comment]
@DKImprowised From what I see in the picture most of the install went fine. IThose messages about sysv-rc-config / chkconfig can be ignored. Those only come up if you had the fog-client installed before and the SmartInstaller removes things before installing again ([code reference](https://github.com/FOGProject/fog-client/blob/master/UniversalInstaller/Linux/LinuxInstall.cs#L35))! I will push a commit to get rid of those messages in the next release.

So what makes you think the fog-client doesn't work? Please take a look at the fog.log file to see if it is able to communicate with your FOG server or not.

**Comment by DKImprowised** [comment]
> Those only come up if you had the fog-client installed before and the SmartInstaller removes things before installing again ([code reference](https://github.com/FOGProject/fog-client/blob/master/UniversalInstaller/Linux/LinuxInstall.cs#L35))!

well, this was the first time only I was installing on my client



> Please take a look at the fog.log file to see if it is able to communicate with your FOG server or not.

also there is no log file being generated:(

**Comment by Sebastian-Roth** [comment]
@DKImprowised But the installer will only run the "uninstall" routines when the directory `/opt/fog-service` exists beforehand.

What output do you get when you run the following command?
```
sudo systemctl start FOGService
sudo systemctl status FOGService
```
Please copy and paste the output your get here.

**Comment by Sebastian-Roth** [comment]
@DKImprowised Can we close this issue?
