### ISSUE TITLE
Cannot Reliably run Snapins

### ISSUE THREAD

**Issue by shaqaruden** [FOGProject/fog-client#132]
I have been finding when trying to run a snapin on a group of Windows computers, I always have a list of anywhere from 1/4 - 1/2 of them that don't actually run. I have to manually go to the computers and restart the FOG Service for the snapins to run, which I found out today is not even always the case. Just now I had scheduled a snapin to run but when manually needing to restart the FOG Service on maybe 10 of them, I happened to check whether the snapin had been applied (Snapin was to modify a registry value) to find that it did not run. I scheduled it again on the computer I checked and waited for FOG Service to pick it up and then it applied it.

**Comment by Sebastian-Roth** [comment]
@shaqaruden Sorry for the late response. Somehow slipped through as we are a very small team of people working on FOG currently.

* Which version of FOG and the fog-client do you use?
* Could you add debug output to the snapin script you run to see if it does start at all?
* What output do you get in `C:\fog.log` when a snapin doesn't run?

**Comment by Sebastian-Roth** [comment]
Closing this now as we haven't heard back yet.
