### ISSUE TITLE
Getting error "Could not get security token"

### ISSUE THREAD

**Issue by jveronese** [FOGProject/fog-client#140]
So we are making a golden image and capturing it via Fog. We have the latest version of the Fog Client installed and for the first few days after capturing the image, the client works just fine. It talks to the Fog server, renames the laptop, and tosses it on the domain. However, after a few days, this stops working altogether and the log starts giving me an error that it "could not get the security token". I have tried several fresh installs, and various versions of the client, but they all have the same issue. Does anyone have any thoughts on what might be happening?

**Comment by Sebastian-Roth** [comment]
@jveronese Please provide more details like the exact FOG version as well as Linux OS and version used. Post relevant parts of the `fog.log` file found on the client machine right from the point where it starts to stop communicating properly. As well you might want to check apache and PHP logs to see if relevant errors occur when it happens.

**Comment by jveronese** [comment]
Apologies, here is the info. Also after a fresh image, it no longer yells about the security token, but that the connections is closed.

FOG Server version - 1.5.9.154
OS- Ubuntu 20.04
Fog-Client - 0.12.2

Log File

```
------------------------------------------------------------------------------
----------------------------------UserTracker---------------------------------
------------------------------------------------------------------------------
 12/13/2022 8:19:26 AM Client-Info Client Version: 0.12.1
 12/13/2022 8:19:26 AM Client-Info Client OS:      Windows
 12/13/2022 8:19:26 AM Client-Info Server Version: 1.5.9.154
 12/13/2022 8:19:26 AM Middleware::Response ERROR: Unable to get subsection
 12/13/2022 8:19:26 AM Middleware::Response ERROR: Object reference not set to an instance of an object.
 12/13/2022 8:19:26 AM Service Sleeping for 60 seconds
 12/13/2022 8:20:26 AM Middleware::Communication URL: https://172.16.8.239/fog/management/index.php?sub=requestClientInfo&configure&newService&json
 12/13/2022 8:20:26 AM Middleware::Communication ERROR: Could not contact FOG server
 12/13/2022 8:20:26 AM Middleware::Communication ERROR: The underlying connection was closed: An unexpected error occurred on a send.
 12/13/2022 8:20:26 AM Middleware::Response Success
 12/13/2022 8:20:26 AM Service ERROR: Invalid promptTime, using default
 12/13/2022 8:20:26 AM Middleware::Communication URL: https://172.16.8.239/fog/management/index.php?sub=requestClientInfo&mac=9C:EB:E8:F7:A8:5F|04:56:E5:51:CD:7C|04:56:E5:51:CD:7D|06:56:E5:51:CD:7C|04:56:E5:51:CD:80&newService&json
 12/13/2022 8:20:26 AM Middleware::Communication ERROR: Could not contact FOG server
 12/13/2022 8:20:26 AM Middleware::Communication ERROR: The underlying connection was closed: An unexpected error occurred on a send.
 12/13/2022 8:20:26 AM Middleware::Response Success
 12/13/2022 8:20:26 AM Middleware::Communication URL: https://172.16.8.239/fog/service/getversion.php?clientver&newService&json
 12/13/2022 8:20:26 AM Service ERROR: Unable to get cycle data
 12/13/2022 8:20:26 AM Service ERROR: The underlying connection was closed: An unexpected error occurred on a send.
 12/13/2022 8:20:26 AM Middleware::Response Success
```

**Comment by Sebastian-Roth** [comment]
@jveronese To me the error `The underlying connection was closed: An unexpected error occurred on a send.` sound pretty much like a basic network/communication issue. Nothing we can do about it. Please make sure the network connection from the client to the FOG server (https://172.16.8.239/fog/) is fine, e.g. open that URL in the browser.

Is there a router between fog-client PC and the server? VPN-tunnels? Bandwidth limiter? Or maybe there is even a proxy configuration applied in your network?

**Comment by Sebastian-Roth** [comment]
@jveronese Do you still need help with this?

**Comment by Sebastian-Roth** [comment]
Closing as there has been no feedback for over a month.
