### ISSUE TITLE
Make sure user input cannot inject malicious commands

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fog-client#143]
Test to see of one can inject malicious commands (e.g. by sending `C:\\Configfile.dat" && del /s /q C:\\Windows && echo "abc` or similar strings).

https://github.com/FOGProject/fog-client/blob/9755290de68ff6eac3e1904770786be2284845a4/Modules/PrinterManager/Windows/WindowsPrinterManager.cs#L41

Can possibly be solved by simply using `Process.StartInfo` as we do in [line 73](https://github.com/FOGProject/fog-client/blob/9755290de68ff6eac3e1904770786be2284845a4/Modules/PrinterManager/Windows/WindowsPrinterManager.cs#L73) already.

References:
https://github.com/microsoft/terminal/issues/13264

**Comment by lukebarone** [comment]
Do we have a test case for this already?

**Comment by lukebarone** [comment]
I believe this to be a non-issue. Running on Windows 11 with Visual Studio 2022, I created a simple C# Windows Form where I can type in whatever I want to the `{cmdLine}` variable, and output to a message box.

The command still returns exit code 0, and nothing further happens. I have it trying to launch Notepad, and it doesn't. I have it trying to output a `dir /a c:\Windows\System32`, and it doesn't.

Here is the code:

```c#
using System.Diagnostics;

namespace WinFormsApp1
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            try
            {
                var cmdLine = "/q " + textBox1.Text;
                using (var proc = Process.Start("rundll32.exe", $" printui.dll,PrintUIEntry {cmdLine}"))
                {
                    proc.WaitForExit(30 * 1000);
                    if (proc.HasExited)
                    {
                        MessageBox.Show("Process return code: " + proc.ExitCode);
                    } else
                    {
                        MessageBox.Show("Process failed to finish");
                    }
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }
    }
}
```

And here's the form:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/6752278/214903219-73cd23cb-8512-47d8-bb05-5867d4bffff8.png">

I also tested with the given command (in a VM), and the Windows folder did not get deleted.

**Comment by Sebastian-Roth** [comment]
@lukebarone Awesome, thanks for testing!

Don't think there is a test case for this yet. Should have.

Interesting you were not able to inject those commands. At first I thought maybe some .Net internals prevent from the injection but there are references to this really being an issue:
https://www.veracode.com/security/dotnet/cwe-78
https://dotnet-security-guard.github.io/SG0001.htm

Made sure you used `... " && ...` when trying to inject the command? Would you be happy to give it another go?

**Comment by lukebarone** [comment]
Both of these, as well as the existing code, expects the Process Name in one parameter, and Arguments in another. I'll try again, but both those links say to use the format `Process.Start($ExeName, $Arguments)`.

Still no change using the format you provided.

**Comment by 0x41c** [comment]
That's great! If that's the case, I'll be sure to close #145. Then Sebastian can close this issue unless of course there's something found that we're missing.
