### ISSUE TITLE
vbs snapin doesn't work after recent windows updates

### ISSUE THREAD

**Issue by kovacsIVgabor** [FOGProject/fog-client#147]
I tried to run a vbs (with cscript.exe) snapin today and got this error in the fog.log:
```
Data::Hash ERROR: Unable to hash file C:\Program files(x86)\FOG\tmp\program.vbs
```
After I deployed the image which was captured in 2023 the snapin worked, so I am sure some windows update causing this.

My original FOG Client version is 0.11.19
I installed the latest release 0.13, which produces the same error.

Please help

**Comment by lukebarone** [comment]
https://www.spiceworks.com/tech/tech-general/news/microsoft-vbscript-deprecation-timeline-windows-updates/amp/

Vbs scripts are deprecated as of this week with the latest Windows Update.

Will likely not fix as it's slated for complete removal.

I suggest moving over to PowerShell. There are lots more resources
available for PS

**Comment by kovacsIVgabor** [comment]
Thank you for your reply.
I kinda expected something like this, and the task was urgent, so I rewrote the script in powershell already.
I feel like last man on Earth using vbs :)
Thank you again.

**Comment by lukebarone** [comment]
No problem. It was bound to happen :)
