### ISSUE TITLE
Build on Windows 10 and 7

### ISSUE THREAD

**Issue by alexandre-lg** [FOGProject/fog-client#43]
Hello,

First, it's necessary to add msbuild in path:
`$env:path += ";C:\Program Files (x86)\MSBuild\14.0\Bin"`

After that, assembly is missing (sorry, I'm French):
`C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1097,5): warning MSB3644: les assemblys de référence pour le framework ".NETFramework,Version=v4.5.1" sont introuvables. Pour résoudre ce problème, installez le SDK ou le Targeting Pack pour cette version de framework ou reciblez votre application vers une version du framework pour laquelle le SDK ou le Targeting Pack est installé. Les assemblys seront résolus à partir du Global Assembly Cache (GAC) et seront utilisés à la place des assemblys de référence. C'est pourquoi votre assembly peut ne pas cibler correctement le framework souhaité. [C:\Users\adale01\Downloads\fog-client-master\Modules\Modules.csproj]`

Thanks for your work and your help!

**Comment by jbob182** [comment]
The build script has been heavily re-written and a revised dependency list is being put together. I will update this issue when all of the changes have been pushed.

**Comment by alexandre-lg** [comment]
Ok thanks, you can close this issue.
