### ISSUE TITLE
Tray icon showing when it should not / tray icon does not open app window

### ISSUE THREAD

**Issue by sluTTYusr** [FOGProject/fog-client#62]
I have just installed the msi package of v0.11.2 in Windows Server 2003 R2 Enterprise.
Commandline was: 
msiexec /i FOGService.msi USETRAY="0" WEBADDRESS="myfogserversIPaddress"

After restarting the server the tray icon shows anyway. When I klick it, it does not open the application window.

**Comment by jbob182** [comment]
The tray does not open any application window currently. It simply shows notifications and the client version number on hover. 

As for the installation issue, can you post your settings.json file located at "C:\Program Files (x86)\FOG\settings.json" (or just Program Files on 32 bit Windows). Feel free to strip out the server address.

**Comment by sluTTYusr** [comment]
Fwiw... the SmartInstaller of the same version does not work at all... thats my impression at least... it does not show any process with the appropriate name and in the services list I cant see the FOG service. Nothing happens.

**Comment by sluTTYusr** [comment]
Thanks... here's the settings.json

> {
  "HTTPS": "0",
  "Tray": "1",
  "Server": "192.168.178.222",
  "WebRoot": "/fog",
  "Version": "0.11.2",
  "Company": "FOG",
  "RootLog": "1",
  "PromptTime": "60",
  "Sleep": "76"
}

Seems like my command line option regarding the tray did not quite make it there :)

**Comment by sluTTYusr** [comment]
I just set "Tray":"0" in the file and restarted the service, voila no tray icon anymore :)

**Comment by jbob182** [comment]
I see on your msiexec command you don't have `/quiet`. Did you install via the msi gui? If so command line arguments don't take affect. They only work in quiet mode.

**Comment by sluTTYusr** [comment]
No, I am pretty sure I used the /quiet option but forgot to post it here. I did not use the GUI.
Anyway... should the SmartInstaller be working in Windows Server 2003 at all?

**Comment by jbob182** [comment]
The SmartInstaller works on most reasonable OS's. However it does require .NET v4.0 and it's support for XP, which is what Server 2003 is built on, is not guaranteed. In fact the entire client is not guaranteed to work on an XP based operating system.

**Comment by mastacontrola** [comment]
Let me add, while the Client is not guaranteed to work on XP, I can assure you it DOES work on XP, but only if running the MSI for the installer, not the smart installer.

**Comment by sluTTYusr** [comment]
Thanks for the clarification. I have .NET v4.0 installed and the MSI installer works, not the SmartInstaller though... exactly as you explained. I did not find this info in [here](https://wiki.fogproject.org/wiki/index.php?title=FOG_Client)

**Comment by mastacontrola** [comment]
That's because XP is no longer supported.  We didn't code to make XP a priorty target.  This would be like saying that the MSI doesn't work on Windows 98, at this point.

**Comment by mastacontrola** [comment]
To know, XP/2003 will not allow auto-updating.

**Comment by sluTTYusr** [comment]
Understood. I am glad the MSI works, though as we have applications that only run on W2K3 32bit
