### ISSUE TITLE
FOGClient new VS legacy on Windows 10

### ISSUE THREAD

**Issue by alexandre-lg** [FOGProject/fog-client#63]
Hello,

I try to install the new FOGClient on a computer with Windows 10 after uninstalling the legacy client (reboot between steps), but it does not work.

No FOGClient installed:
![](https://framapic.org/XoDk87vrBoJL/RxvEofPPVSkT)

When I try to install FOGClient v0.11.2, same with old version and MSI or SmartInstaller:
![](https://framapic.org/IiUIVeNNhJya/HGlf8fPEA7fj)

Thanks for the help

**Comment by alexandre-lg** [comment]
Ok, I can install and uninstall FOGClient v0.9.11 but can't update to or install FOGClient 0.11.2...

**Comment by mastacontrola** [comment]
https://forums.fogproject.org/topic/7758/client-install-issues-legacy-uninstall/16

There's a tailing legacy registry script that's not being removed properly.  This posting should help you find and fix this issue for you.

**Comment by alexandre-lg** [comment]
Hello and thanks but key `{91C5D423-B6AB-4EAB-8F17-2BB3AE162CA1}` does not exist

**Comment by mastacontrola** [comment]
I'm going to guess the version of windows is Windows 7 64 bit?

In that case you may need to look in HLKM\Software\WOW6432Node

**Comment by alexandre-lg** [comment]
As I said , it is under Windows 10 I meet the problem. This is actually version 64 .

**Comment by jbob182** [comment]
It is concerning that the legacy client has leftover that registry key. Another user reported this issue on one of their machines. However, it seems to happen rarely and we can't replicate.
