### ISSUE TITLE
Snapin Pack: Set working directory to FOG_SNAPIN_PATH

### ISSUE THREAD

**Issue by TFenby** [FOGProject/fog-client#65]
Being able to run a simple script that makes use of the other files in a snapin pack would be hugely useful, but as it is that can only be done by statically referencing the FOG "tmp" directory within the script. Can SnapinClient.cs be modified such that the subprocesses it spawns are started w/ their working directory set to FOG_SNAPIN_PATH?
See here: https://stackoverflow.com/questions/114928/net-process-start-default-directory

I'd do it myself if I had the proper dev tools in place, but for such a tiny change I figured a ticket would be acceptable.

**Comment by mastacontrola** [comment]
We will certainly add this feature, but it is not worth a whole new release just for this small change. You can simply get your scripts current location and change your working directory to that. The majority of languages have some capability of getting the scripts file path.

**Comment by TFenby** [comment]
Makes sense. Will do that in the meantime. Thanks!
