### ISSUE TITLE
HostnameChanger Users still logged in and enforce is disabled, delaying any further actions

### ISSUE THREAD

**Issue by wayneworkman** [FOGProject/fog-client#71]
But, who is logged in?

Can the client write who is logged in - within the logs?

We have a potential issue where a FOG Community member said nobody is logged into the computer - yet the computer does not rename or join. This is with the  “Make changes even when users are logged on?” feature is turned off.

[Reference link](https://forums.fogproject.org/topic/8382/snapins-failing-due-to-hostname-not-changing)

**Comment by jbob182** [comment]
See https://forums.fogproject.org/topic/8382/snapins-failing-due-to-hostname-not-changing . The debugger can be used to retrieve a listing of users.
