### ISSUE TITLE
Change Hostname Ubuntu 16.04

### ISSUE THREAD

**Issue by Hexaflexagon** [FOGProject/fog-client#78]
Hello,

i installed the newest FOG R 36 Version and the newest Client on a Ubuntu 16.04 Computer, but the hostname wasn't changed after a reboot.
I tried it on Windows 10 and this works fine.

**Comment by jbob182** [comment]
Please provide the corresponding `fog.log` for  the Ubuntu machine having this issue (found in `/opt/fog-service/fog.log`).

**Comment by Hexaflexagon** [comment]
Thanks, i found my problem.
I used the automatic user login :/

**Comment by jbob182** [comment]
You can also disable the option to wait while users are logged in as well (found in the web portal).
