### ISSUE TITLE
Not autologging out - Windows 10

### ISSUE THREAD

**Issue by 88fingerslukee** [FOGProject/fog-client#87]
Hi there,

Is this the right place for this question or should this be in the fog forum?

I'm having an issue with the client not logging me out on Windows 10.  The .fog_user log has stalled at the last attempt to logout but there are no error messages. The other log file (fog) is still updating.  Here are the last lines of the fog_user log.

`------------------------------------------------------------------------------
----------------------------------AutoLogOut----------------------------------
------------------------------------------------------------------------------
 6/23/2017 8:52 PM Client-Info Client Version: 0.11.12
 6/23/2017 8:52 PM Client-Info Client OS:      Windows
 6/23/2017 8:52 PM Client-Info Server Version: 1.4.1
 6/23/2017 8:52 PM Middleware::Response Success
 6/23/2017 8:52 PM Bus Emmiting message on channel: Notification
 6/23/2017 8:52 PM Power Creating shutdown request
 6/23/2017 8:52 PM Power Parameters: /l
------------------------------------------------------------------------------`

**Comment by Sebastian-Roth** [comment]
Sure this went to the forums and was answered there. Closing.
