### ISSUE TITLE
Default webroot setting when command line parameters are supplied to the SmartInstaller

### ISSUE THREAD

**Issue by Sebastian-Roth** [FOGProject/fog-client#99]
SmartInstaller command line paramters `--server=` and `--webroot=` default to be empty if only one **but not** both parameters are supplied. [Forum post](https://forums.fogproject.org/topic/10962/fog-client-ignoring-webroot/3) and [source code](https://github.com/FOGProject/fog-client/blob/master/UniversalInstaller/UniversalInstaller.cs#L48) reference.

**Comment by FinancedHydra** [comment]
I suppose this is a good time to make the appropriate unit tests for the SmartInstaller anyways

**Comment by FinancedHydra** [comment]
PR #101 should patch this. I will test shortly
